version: '3.8'

services:
  resume-generator:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - INPUT_YAML=${INPUT_YAML:-data/resume.yaml}
      - OUTPUT_TEX=${OUTPUT_TEX:-data/resume.tex}
    command: ${INPUT_YAML:-data/resume.yaml} ${OUTPUT_TEX:-data/resume.tex} 